In [1]:
import pandas as pd

In [2]:
jan = pd.read_csv('DEMACRO/2020/jan2020.csv', sep = ';')
fev = pd.read_csv('DEMACRO/2020/fev2020.csv', sep = ';')
mar = pd.read_csv('DEMACRO/2020/mar2020.csv', sep = ';')
abr = pd.read_csv('DEMACRO/2020/abr2020.csv', sep = ';')
mai = pd.read_csv('DEMACRO/2020/mai2020.csv', sep = ';')
jun = pd.read_csv('DEMACRO/2020/jun2020.csv', sep = ';')
jul = pd.read_csv('DEMACRO/2020/jul2020.csv', sep = ';')

In [3]:
todos = pd.concat([jan, fev, mar, abr, mai, jun, jul])

In [4]:
todos.head(100)

,ANO_BO,NUM_BO,NUMERO_BOLETIM,BO_INICIADO,BO_EMITIDO,DATAOCORRENCIA,HORAOCORRENCIA,PERIDOOCORRENCIA,DATACOMUNICACAO,DATAELABORACAO,...,PLACA_VEICULO,UF_VEICULO,CIDADE_VEICULO,DESCR_COR_VEICULO,DESCR_MARCA_VEICULO,ANO_FABRICACAO,ANO_MODELO,DESCR_TIPO_VEICULO,QUANT_CELULAR,MARCA_CELULAR
0,2020,36,36/2020,01/01/2020 01:41:04,01/01/2020 01:40:45,31/12/2019,19:00,A NOITE,01/01/2020,01/01/2020 01:41:04,...,CYW3705,SP,GUARULHOS,Cinza,FIAT/UNO MILLE EX,2000.0,NaN,AUTOMOVEL,NaN,NaN
1,2020,1,1/2020,01/01/2020 01:41:41,01/01/2020 04:30:32,31/12/2019,23:00,A NOITE,01/01/2020,01/01/2020 01:41:41,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN
2,2020,1,1/2020,01/01/2020 01:41:41,01/01/2020 04:30:32,31/12/2019,23:00,A NOITE,01/01/2020,01/01/2020 01:41:41,...,CDD8712,SP,S.BERNARDO DO CAMPO,Azul,FIAT/UNO CS,1987.0,1988.0,AUTOMOVEL,NaN,NaN
3,2020,1,1/2020,01/01/2020 01:41:41,01/01/2020 04:30:32,31/12/2019,23:00,A NOITE,01/01/2020,01/01/2020 01:41:41,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN
4,2020,1,1/2020,01/01/2020 01:41:41,01/01/2020 04:30:32,31/12/2019,23:00,A NOITE,01/01/2020,01/01/2020 01:41:41,...,CDD8712,SP,S.BERNARDO DO CAMPO,Azul,FIAT/UNO CS,1987.0,1988.0,AUTOMOVEL,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2020,26,26/2020,03/01/2020 08:32:49,03/01/2020 09:24:34,02/01/2020,13:00,A TARDE,03/01/2020,03/01/2020 08:32:49,...,CYY5151,SP,GUARULHOS,Vermelho,GM/CARAVAN COMODORO SL/E,1989.0,1990.0,AUTOMOVEL,NaN,NaN
96,2020,26,26/2020,03/01/2020 08:32:49,03/01/2020 09:24:34,02/01/2020,13:00,A TARDE,03/01/2020,03/01/2020 08:32:49,...,CYY5533,SP,GUARULHOS,Cinza,GM/CARAVAN COMODORO,1982.0,1982.0,AUTOMOVEL,NaN,NaN
97,2020,26,26/2020,03/01/2020 08:32:49,03/01/2020 09:24:34,02/01/2020,13:00,A TARDE,03/01/2020,03/01/2020 08:32:49,...,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN
98,2020,26,26/2020,03/01/2020 08:32:49,03/01/2020 09:24:34,02/01/2020,13:00,A TARDE,03/01/2020,03/01/2020 08:32:49,...,CYY3355,SP,GUARULHOS,Bege,GM/CARAVAN,1977.0,1977.0,AUTOMOVEL,NaN,NaN
99,2020,26,26/2020,03/01/2020 08:32:49,03/01/2020 09:24:34,02/01/2020,13:00,A TARDE,03/01/2020,03/01/2020 08:32:49,...,CYY5151,SP,GUARULHOS,Vermelho,GM/CARAVAN COMODORO SL/E,1989.0,1990.0,AUTOMOVEL,NaN,NaN

In [5]:
todos.drop_duplicates(subset ="NUM_BO", keep = False, inplace = True)

In [6]:
todos = todos.drop(['NUM_BO', 'NUMERO_BOLETIM', 'PLACA_VEICULO', 'UF_VEICULO', 'CIDADE_VEICULO', 'MARCA_CELULAR', 'IDADE', 'SEXO', 'TIPOPESSOA', 'STATUS', 'DESDOBRAMENTO', 'FLAGRANTE', 'DESCRICAOLOCAL', 'QUANT_CELULAR', 'BO_AUTORIA', 'NUMERO_BOLETIM_PRINCIPAL', 'EXAME', 'SOLUCAO', 'NOMEPESSOA', 'VITIMAFATAL', 'RG', 'RG_UF', 'NATURALIDADE', 'NACIONALIDADE', 'DATANASCIMENTO', 'ESTADOCIVIL', 'PROFISSAO', 
'GRAUINSTRUCAO', 'CORCUTIS', 'NATUREZAVINCULADA', 'TIPOVINCULO', 'RELACIONAMENTO', 'PARENTESCO'], axis = 1)

In [7]:
todos = todos.drop(['DELEGACIA_NOME', 'DELEGACIA_CIRCUNSCRICAO', 'ESPECIE', 'RUBRICA'], axis = 1)

In [8]:
for col in todos:
    print(col)

ANO_BO
BO_INICIADO
BO_EMITIDO
DATAOCORRENCIA
HORAOCORRENCIA
PERIDOOCORRENCIA
DATACOMUNICACAO
DATAELABORACAO
LOGRADOURO
NUMERO
BAIRRO
CIDADE
UF
LATITUDE
LONGITUDE
DESCR_COR_VEICULO
DESCR_MARCA_VEICULO
ANO_FABRICACAO
ANO_MODELO
DESCR_TIPO_VEICULO

In [9]:
todos.dtypes

ANO_BO                   int64
BO_INICIADO             object
BO_EMITIDO              object
DATAOCORRENCIA          object
HORAOCORRENCIA          object
PERIDOOCORRENCIA        object
DATACOMUNICACAO         object
DATAELABORACAO          object
LOGRADOURO              object
NUMERO                   int64
BAIRRO                  object
CIDADE                  object
UF                      object
LATITUDE                object
LONGITUDE               object
DESCR_COR_VEICULO       object
DESCR_MARCA_VEICULO     object
ANO_FABRICACAO         float64
ANO_MODELO             float64
DESCR_TIPO_VEICULO      object
dtype: object

In [10]:
todos.to_csv('DADOS/furtos_metro_2020.csv', index = False)