# extract

In [1]:
import pandas as pd

In [2]:
cap_2018 = pd.read_csv('DADOS/BASES_COMPILADAS/furtos_capital_2018.csv', sep = ',')
cap_2019 = pd.read_csv('DADOS/BASES_COMPILADAS/furtos_capital_2019.csv', sep = ',')
cap_2020 = pd.read_csv('DADOS/BASES_COMPILADAS/furtos_capital_2020.csv', sep = ',')
met_2018 = pd.read_csv('DADOS/BASES_COMPILADAS/furtos_metro_2018.csv', sep = ',')
met_2019 = pd.read_csv('DADOS/BASES_COMPILADAS/furtos_metro_2019.csv', sep = ',')
met_2020 = pd.read_csv('DADOS/BASES_COMPILADAS/furtos_metro_2020.csv', sep = ',')

In [5]:
Df = pd.concat([cap_2018, cap_2019, cap_2020, met_2018, met_2019, met_2020])

In [6]:
Df.sample(20)

,ANO_BO,BO_INICIADO,BO_EMITIDO,DATAOCORRENCIA,HORAOCORRENCIA,PERIDOOCORRENCIA,DATACOMUNICACAO,DATAELABORACAO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,LATITUDE,LONGITUDE,DESCR_COR_VEICULO,DESCR_MARCA_VEICULO,ANO_FABRICACAO,ANO_MODELO,DESCR_TIPO_VEICULO
4488,2020.0,27/05/2020 21:40:48,27/05/2020 21:43:30,27/05/2020,19:30,A NOITE,27/05/2020,27/05/2020 21:40:48,RUA DOIS DE JULHO,97.0,IPIRANGA,S.PAULO,SP,NaN,NaN,Vermelho,CHEVROLET/CELTA 1.0L LT,2013.0,NaN,AUTOMOVEL
10521,2019.0,03/09/2019 16:40:32,03/09/2019 16:40:31,03/09/2019,13:20,A TARDE,03/09/2019,03/09/2019 16:40:32,RUA HENRIQUE SERTORIO,196.0,TATUAPE,S.PAULO,SP,"-23,538482132375","-46,5782018329166",Amarelo,HONDA/XRE 300,2010.0,NaN,MOTOCICLO
12902,2018.0,13/08/2018 12:10:56,13/08/2018 12:11:11,11/08/2018,11:00,PELA MANHÃ,13/08/2018,13/08/2018 12:10:56,RUA ALVINÓPOLIS,453.0,VILA BEATRIZ,S.PAULO,SP,NaN,NaN,Prata,I/HYUNDAI VERACRUZ 3.8V6,2010.0,NaN,AUTOMOVEL
11050,2018.0,15/11/2018 14:48:28,15/11/2018 15:12:24,14/11/2018,21:40,A NOITE,15/11/2018,15/11/2018 14:48:28,AVENIDA BENEDITO ALVES TURÍBIO,1171.0,BANDEIRAS,OSASCO,SP,"-23,5503482479981","-46,8155079751455",Vermelho,FIAT/UNO ELETRONIC,1995.0,1996.0,AUTOMOVEL
5955,2020.0,22/06/2020 20:48:54,22/06/2020 20:48:11,22/06/2020,19:10,A NOITE,22/06/2020,22/06/2020 20:48:54,RUA JOAO BATISTA MONTE,27.0,PENHA,S.PAULO,SP,NaN,NaN,Branco,I/CHEV CRUZE LTZ HB AT,2017.0,NaN,AUTOMOVEL
7696,2019.0,25/06/2019 12:34:53,25/06/2019 12:35:21,25/06/2019,01:30,DE MADRUGADA,25/06/2019,25/06/2019 12:34:53,RUA SEBASTIAO BARBOSA,172.0,AGUA RASA,S.PAULO,SP,"-23,5537539928975","-46,5738207008222",Branco,FORD/KA SE 1.0 HA,2019.0,NaN,AUTOMOVEL
11063,2019.0,20/08/2019 20:00:21,20/08/2019 20:00:59,20/08/2019,18:00,A NOITE,20/08/2019,20/08/2019 20:00:21,RUA JOAO DAUDT FILHO,167.0,BRASILANDIA,S.PAULO,SP,"-23,4726802067396","-46,6920225843103",Branco,NaN,2000.0,NaN,AUTOMOVEL
10201,2018.0,26/06/2018 16:53:04,26/06/2018 16:53:31,26/06/2018,02:00,DE MADRUGADA,26/06/2018,26/06/2018 16:53:04,RUA CABO JOEL LEITE,635.0,ITAQUERA,S.PAULO,SP,NaN,NaN,Prata,HONDA/FIT LX FLEX,2009.0,NaN,AUTOMOVEL
9135,2018.0,03/10/2018 12:38:56,03/10/2018 12:53:04,03/10/2018,08:40,PELA MANHÃ,03/10/2018,03/10/2018 12:38:56,RUA BELA VISTA,386.0,CENTRO,S.BERNARDO DO CAMPO,SP,"-23,7122810189759","-46,5461973783854",Vermelho,YAMAHA/YS150 FAZER SED,2018.0,2019.0,MOTOCICLO
13277,2019.0,16/10/2019 10:20:53,16/10/2019 10:39:34,15/10/2019,19:00,A NOITE,16/10/2019,16/10/2019 10:20:53,LARGO DO SOCORRO,78.0,SOCORRO,S.PAULO,SP,"-23,66559490044","-46,712270333531",Preta,HONDA/CG 160 FAN ESDI,2016.0,2016.0,MOTOCICLO
10530,2018.0,02/11/2018 18:52:41,02/11/2018 18:52:33,02/11/2018,09:30,PELA MANHÃ,02/11/2018,02/11/2018 18:52:41,RUA GANA,262.0,PARQUE NOVO ORATÓRIO I,S.ANDRE,SP,"-23,632653310931","-46,4970380473448",Branco,FIAT/UNO 1.0,1992.0,NaN,AUTOMOVEL
499,2020.0,21/01/2020 13:23:11,21/01/2020 13:22:56,20/01/2020,19:00,A NOITE,21/01/2020,21/01/2020 13:23:11,RUA JIRO MARUYAMA,231.0,J OLIVEIRA,TABOAO DA SERRA,SP,"-23,6217916775525","-46,7716746558813",Bege,I/GM CLASSIC LIFE,2006.0,NaN,AUTOMOVEL
9489,2019.0,18/08/2019 12:53:15,18/08/2019 12:52:55,17/08/2019,12:45,A TARDE,18/08/2019,18/08/2019 12:53:15,RUA ARRAIAL VELHO,26.0,ARICANDUVA,S.PAULO,SP,"-23,5611310986555","-46,5218290207726",Preta,GM/MERIVA PREMIUM,2008.0,NaN,AUTOMOVEL
12106,2018.0,30/07/2018 11:16:07,30/07/2018 11:15:51,26/07/2018,15:30,A TARDE,30/07/2018,30/07/2018 11:16:07,RUA DA BICA,170.0,FREGUESIA DO Ó,S.PAULO,SP,NaN,NaN,Preta,FIAT/PALIO WEEK TREKKING,2009.0,NaN,AUTOMOVEL
7609,2019.0,22/06/2019 23:20:25,22/06/2019 23:21:34,22/06/2019,13:30,A TARDE,22/06/2019,22/06/2019 23:20:25,RUA PORTO DA FOLHA,720.0,VILA MATILDE,S.PAULO,SP,"-23,535110539","-46,499942185",Verde,NaN,1996.0,NaN,Não Informado
15916,2019.0,01/12/2019 23:45:38,01/12/2019 23:45:04,01/12/2019,20:25,A NOITE,01/12/2019,01/12/2019 23:45:38,RUA ANTONIO NUNES DE AZEVEDO,148.0,CAPAO REDONDO,S.PAULO,SP,"-23,661824058","-46,791346355",Prata,HONDA/CBX 250 TWISTER,2005.0,NaN,MOTOCICLO
8912,2018.0,05/06/2018 19:41:47,05/06/2018 19:41:47,05/06/2018,NaN,PELA MANHÃ,05/06/2018,05/06/2018 19:41:47,RUA MILTON DA CRUZ,659.0,SAPOPEMBA,S.PAULO,SP,"-23,606703615","-46,507601705",Vermelho,FORD/FIESTA FLEX,2013.0,2013.0,AUTOMOVEL
8557,2020.0,28/07/2020 14:09:35,28/07/2020 14:09:29,27/07/2020,08:00,PELA MANHÃ,28/07/2020,28/07/2020 14:09:35,AVENIDA CONDESSA ELISABETH DE ROBIANO,6000.0,TATUAPE,S.PAULO,SP,"-23,523562281","-46,5580252899999",Preta,REB/KORG KR500 JS,2005.0,NaN,Não Informado
7737,2019.0,20/07/2019 19:05:54,20/07/2019 19:06:36,20/07/2019,14:00,A TARDE,20/07/2019,20/07/2019 19:05:54,AVENIDA MARECHAL EURICO GASPAR DUTRA,1678.0,TUCURUVI,S.PAULO,SP,"-23,486026301","-46,6106593229999",Cinza,NaN,2017.0,NaN,AUTOMOVEL
11997,2019.0,04/09/2019 00:52:43,04/09/2019 00:52:43,03/09/2019,15:00,A TARDE,04/09/2019,04/09/2019 00:52:43,PRAÇA ALBERTO LION,715.0,CAMBUCI,S.PAULO,SP,"-23,5638982039999","-46,611973828",Cinza,NaN,2012.0,NaN,AUTOMOVEL

### Breve análise dos dados

In [7]:
Df.shape

(84312, 20)

In [8]:
Df.dtypes

ANO_BO                 float64
BO_INICIADO             object
BO_EMITIDO              object
DATAOCORRENCIA          object
HORAOCORRENCIA          object
PERIDOOCORRENCIA        object
DATACOMUNICACAO         object
DATAELABORACAO          object
LOGRADOURO              object
NUMERO                 float64
BAIRRO                  object
CIDADE                  object
UF                      object
LATITUDE                object
LONGITUDE               object
DESCR_COR_VEICULO       object
DESCR_MARCA_VEICULO     object
ANO_FABRICACAO         float64
ANO_MODELO             float64
DESCR_TIPO_VEICULO      object
dtype: object

In [9]:
Df.isnull().sum()

ANO_BO                     0
BO_INICIADO                0
BO_EMITIDO                 0
DATAOCORRENCIA             0
HORAOCORRENCIA         17669
PERIDOOCORRENCIA           0
DATACOMUNICACAO            0
DATAELABORACAO             0
LOGRADOURO              1181
NUMERO                     0
BAIRRO                  3751
CIDADE                     0
UF                         0
LATITUDE               12208
LONGITUDE              12208
DESCR_COR_VEICULO       7538
DESCR_MARCA_VEICULO    12723
ANO_FABRICACAO          8468
ANO_MODELO             63521
DESCR_TIPO_VEICULO      7660
dtype: int64

# Transform

#### Deletando colunas com dados inrrelevantes e tratando os nulos

In [10]:
Df_transform = todos.drop(["HORAOCORRENCIA","LATITUDE","LONGITUDE"], axis = 1)

In [11]:
Df_transform[['LOGRADOURO']]=Df_transform[['LOGRADOURO']].fillna('')
Df_transform[['BAIRRO']]=Df_transform[['BAIRRO']].fillna('')
Df_transform[['DESCR_COR_VEICULO']]=Df_transform[['DESCR_COR_VEICULO']].fillna('')
Df_transform[['DESCR_MARCA_VEICULO']]=Df_transform[['DESCR_MARCA_VEICULO']].fillna('')
Df_transform[['ANO_FABRICACAO']]=Df_transform[['ANO_FABRICACAO']].fillna('')
Df_transform[['ANO_MODELO']]=Df_transform[['ANO_MODELO']].fillna('')
Df_transform[['DESCR_TIPO_VEICULO']]=Df_transform[['DESCR_TIPO_VEICULO']].fillna('')
print(Df_transform.isnull().sum())

ANO_BO                 0
BO_INICIADO            0
BO_EMITIDO             0
DATAOCORRENCIA         0
PERIDOOCORRENCIA       0
DATACOMUNICACAO        0
DATAELABORACAO         0
LOGRADOURO             0
NUMERO                 0
BAIRRO                 0
CIDADE                 0
UF                     0
DESCR_COR_VEICULO      0
DESCR_MARCA_VEICULO    0
ANO_FABRICACAO         0
ANO_MODELO             0
DESCR_TIPO_VEICULO     0
dtype: int64

In [12]:
Df_transform.tail()

,ANO_BO,BO_INICIADO,BO_EMITIDO,DATAOCORRENCIA,PERIDOOCORRENCIA,DATACOMUNICACAO,DATAELABORACAO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,DESCR_COR_VEICULO,DESCR_MARCA_VEICULO,ANO_FABRICACAO,ANO_MODELO,DESCR_TIPO_VEICULO
6624,2020.0,31/07/2020 18:22:24,31/07/2020 18:22:11,30/07/2020,A NOITE,31/07/2020,31/07/2020 18:22:24,RUA CAPITAO LEONCIO AROUCHE DE TOLEDO,76.0,VL MOGILAR,MOGI DAS CRUZES,SP,Preta,FIAT/SIENA ESSENCE 1.6,2014,,AUTOMOVEL
6625,2020.0,31/07/2020 18:19:33,31/07/2020 18:32:02,27/07/2020,DE MADRUGADA,31/07/2020,31/07/2020 18:19:33,RUA SÃO PAULO DE OLIVEIRA,700.0,CUMBICA,GUARULHOS,SP,Vermelho,FIAT/FIAT UNO SX,1984,,AUTOMOVEL
6626,2020.0,31/07/2020 19:56:53,31/07/2020 19:56:52,31/07/2020,A TARDE,31/07/2020,31/07/2020 19:56:53,ESTRADA DA GABIROBA,543.0,AREA RURAL,CARAPICUIBA,SP,Vermelho,HONDA/CG 150 FAN ESI,2012,,MOTOCICLO
6627,2020.0,31/07/2020 19:30:59,31/07/2020 19:57:59,31/07/2020,PELA MANHÃ,31/07/2020,31/07/2020 19:30:59,,0.0,JD COPACABANA,POA,SP,Prata,VW/GOL 1.6 POWER,2006,2007,AUTOMOVEL
6628,2020.0,31/07/2020 21:03:54,31/07/2020 21:14:49,31/07/2020,A TARDE,31/07/2020,31/07/2020 21:03:54,RUA NOSSA SENHORA DE APARECIDA,55.0,JD SÃO LUIZ,COTIA,SP,Branco,I/HYUNDAI SANTA FE 2.4,2011,2012,CAMIONETA

### Passando datas para formato Datetime() e núneros para int()

In [13]:
Df_transform['BO_INICIADO'] = pd.to_datetime(Df_transform['BO_INICIADO'])
Df_transform['BO_EMITIDO'] = pd.to_datetime(Df_transform['BO_EMITIDO'])
Df_transform['DATACOMUNICACAO'] = pd.to_datetime(Df_transform['DATACOMUNICACAO'])
Df_transform['DATAOCORRENCIA'] = pd.to_datetime(Df_transform['DATAOCORRENCIA'], errors="ignore")

In [14]:
convert_dict = {'ANO_BO':int,'NUMERO':int}
Df_transform = Df_transform.astype(convert_dict)


print(Df_transform.dtypes)

ANO_BO                          int32
BO_INICIADO            datetime64[ns]
BO_EMITIDO             datetime64[ns]
DATAOCORRENCIA                 object
PERIDOOCORRENCIA               object
DATACOMUNICACAO        datetime64[ns]
DATAELABORACAO                 object
LOGRADOURO                     object
NUMERO                          int32
BAIRRO                         object
CIDADE                         object
UF                             object
DESCR_COR_VEICULO              object
DESCR_MARCA_VEICULO            object
ANO_FABRICACAO                 object
ANO_MODELO                     object
DESCR_TIPO_VEICULO             object
dtype: object

In [15]:
Df_transform.head()

,ANO_BO,BO_INICIADO,BO_EMITIDO,DATAOCORRENCIA,PERIDOOCORRENCIA,DATACOMUNICACAO,DATAELABORACAO,LOGRADOURO,NUMERO,BAIRRO,CIDADE,UF,DESCR_COR_VEICULO,DESCR_MARCA_VEICULO,ANO_FABRICACAO,ANO_MODELO,DESCR_TIPO_VEICULO
0,2018,2018-01-01 09:49:13,2018-01-01 10:17:56,01/01/2018,DE MADRUGADA,2018-01-01,01/01/2018 09:49:13,,0,GRAJAU,S.PAULO,SP,Prata,HYUNDAI/HB20 1.0M 1.0 M,2013,2014,AUTOMOVEL
1,2017,2018-01-01 11:12:21,2018-01-01 11:12:21,30/12/2017,A TARDE,2017-12-31,01/01/2018 11:12:21,RUA CASTRO AVELAENS,70,SAPOPEMBA,S.PAULO,SP,Prata,PEUGEOT/206 16 PRESEN FX,2005,2005,AUTOMOVEL
2,2017,2018-01-01 11:58:07,2018-01-01 11:58:07,30/12/2017,A TARDE,2017-12-31,01/01/2018 11:58:07,Praca Angelo Rivetti,690,Lapa,S.PAULO,SP,Cinza,GM/MERIVA EXPRESSION,2012,2012,AUTOMOVEL
3,2018,2018-01-01 15:27:01,2018-01-01 15:27:01,31/12/2017,DE MADRUGADA,2018-01-01,01/01/2018 15:27:01,Av presidente castelo branco,9127,Vila mirim,S.PAULO,SP,Vermelho,VW/GOL GLI 1.8,1997,1997,AUTOMOVEL
4,2018,2018-02-01 11:07:13,2018-02-01 11:31:32,01/01/2018,DE MADRUGADA,2018-02-01,02/01/2018 11:07:13,RUA TAKA,129,VILA MARIA,S.PAULO,SP,Bege,FORD/FORD F 4000,1986,1986,CAMINHÃO

# Load

In [16]:
import pyodbc

In [17]:
connection = pyodbc.connect("DSN = SQLServer")
if connection:
    print("conectado ao SQL!\n")
try:
    with connection.cursor() as cursor:
        sql = "select * FROM dw.dbo.vW_ANO_BO"
        cursor.excute(sql)
        tabela = cursor.fetchall()
        print(tabela)
finally:
    conection.close()

InterfaceError: ('IM002', '[IM002] [Microsoft][ODBC Driver Manager] Nome da fonte de dados não encontrado e nenhum driver padrão especificado (0) (SQLDriverConnect)')